spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Test
    username: root
    password: denys
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl_auto: none

    #for initialization DB schema, and filling in it with data from data.sql later
    sql.init.mode: always

  #swagger
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
